### ISSUE TITLE
Pocketbase v0.23 support

### ISSUE THREAD

**Issue by Plorenzo** [patmood/pocketbase-typegen#102]
Pocketbase [v0.23.0-rc](https://github.com/pocketbase/pocketbase/releases/tag/v0.23.0-rc) is out and comes with significant changes to the collections. 

This changes are currently breaking `pocketbase-typegen` 

<details><summary>Details</summary>
<p>

```
$ pnpm run typegen

> ui@0.0.1 typegen /Users/plorenzo/dev/.../ui
> pocketbase-typegen --db ../pb_data/data.db --out ./src/lib/pocketbase/pocketbase-types.ts

undefined:1
undefined
^

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at file:///Users/plorenzo/dev/.../ui/node_modules/.pnpm/pocketbase-typegen@1.2.1_encoding@0.1.13/node_modules/pocketbase-typegen/dist/index.js:20:18
    at Array.map (<anonymous>)
    at fromDatabase (file:///Users/plorenzo/.../ui/node_modules/.pnpm/pocketbase-typegen@1.2.1_encoding@0.1.13/node_modules/pocketbase-typegen/dist/index.js:18:17)
    at async main (file:///Users/plorenzo/dev/.../ui/node_modules/.pnpm/pocketbase-typegen@1.2.1_encoding@0.1.13/node_modules/pocketbase-typegen/dist/index.js:288:14)

Node.js v20.18.0
```

</p>
</details> 

Are there any plans to update this package ?  

To be clear Im not demanding that this happens, just asking so I can plan what to do for my project :) 

Thanks!

**Comment by skowrons** [comment]
For know you could use my forked version: https://github.com/skowrons/pocketbase-typegen
Be aware that you currently need to use the following new npx command:

```shell
npx github:skowrons/pocketbase-typegen --db ./pb_data/data.db --out pocketbase-types.ts
```

**Comment by patmood** [comment]
@skowrons why not do a PR?

**Comment by skowrons** [comment]
@patmood I didn't realize it was still being maintained. My mistake! I'll create a merge request today. ^^

**Comment by skowrons** [comment]
@patmood I did not realized this package was still actively maintained? ^^

**Comment by patmood** [comment]
Doing my best! It only needs updates when there's a breaking PB change. I haven't had the time to look into the latest update but if you have it working, create a PR and lets it it published! I appreciate the contributions

**Comment by skowrons** [comment]
@patmood great! If you need any help with the other issues I linked in my PR please feel free to assign me to them and I will create an PR.
