### ISSUE TITLE
Proposal: JSON field generics

### ISSUE THREAD

**Issue by benallfree** [patmood/pocketbase-typegen#11]
This is meant to capture the issue I mentioned in https://github.com/patmood/pocketbase-typegen/issues/2.

Currently:

```ts
export type InstancesRecord = {
	myJson?: null | unknown
}
```

Maybe there could be something like this instead:

```ts
export type InstancesRecord<TMyJson=unknown> = {
	myJson?: null | TMyJson
}
```

**Comment by patmood** [comment]
Added in `1.0.10` 🚀
