### ISSUE TITLE
Proposal: use type aliases instead of base types for all fields

### ISSUE THREAD

**Issue by benallfree** [patmood/pocketbase-typegen#12]
I learned this one from the puppeteer team:

Instead of 

```ts
export type MyRecord = {
   id: string
   created: string
   updated: string
}
```

Do this

```ts
export type RecordId = string
export type IsoDate = string

export type MyRecord = {
   id: RecordId
   created: IsoDate
   updated: IsoDate
}
```

Benefits:

* Clear intent - `string` or `number` can be ambiguous
* Ability to [brand](https://github.com/kourge/ts-brand) the types later if desired by user without changing them everywhere

**Comment by patmood** [comment]
This is a good addition 👍 I'll add it
