### ISSUE TITLE
Proposal: output multiple files and create a base package

### ISSUE THREAD

**Issue by benallfree** [patmood/pocketbase-typegen#13]
After considering #11 and #12  and #9, it might also be wise to output multiple typings and a base package like this:

```ts
// pocketbase-typegen package

export type RecordId = string
export type IsoDate = string

export type RecordBase = {
   id: RecordId
   created: IsoDate
   updated: IsoDate
}

export const pocketNow = () : IsoString => new Date().toISOString()
```

Then, make it output multiple files like this:

```ts
// <RecordType>_Abstract.ts
// WARNING: AUTOGENERATED, DO NOT EDIT
import { RecordBase } from 'pocketbase-typegen'
import { Jsonifiable } from 'type-fest'  // https://github.com/sindresorhus/type-fest/pull/492/files

export type OrderNumber = number
export type MyRecord_Abstract<TMyJson extends Jsonifiable> = RecordBase & {
   orderNumber: OrderNumber
   myJson: TMyJson
}
```

```ts
// <RecordType>.ts
// GENERATED ONCE ONLY. YOU MAY EDIT THIS FILE.
import { MyRecord_Abstract } from './MyRecord_Abstract'

export type MyJsonField = {
   foo: string
   baz: number
}
export type MyRecord = MyRecord_Abstract<MyJsonField>
```

Then if the user adds a field, the Abstract class will be regenerated. If the field changes the generic signature, they'll  need to update the concrete type with a new generic.

**Comment by patmood** [comment]
I'm hesitant to add this kind of complexity for JSON fields, which are not strongly typed. Now that generics are added the user can easily do this themselves. There's not much value in generating a file for editing.

Similarly, I'm not sure what value a RecordBase type adds when everything is generated. I'd rather keep it simple while pocketbase matures.

I've seen `pocketNow` in a few of your issues, how does that get used?

**Comment by benallfree** [comment]
The purpose of a separate abstract base type is so you don't have to keep repeating the generics signature every time you use the type. 

```ts
export type OrdersRecord<Tdata = unknown> = {
  id: string
  amount: number
  data: null | Tdata // JSON type in pocketbase
  payment_method: "credit_card" | "paypal" | "crypto" // Multiple choice in pocketbase
}
```

The first thing I would do in my own code is make a type alias with the generic arguments defined, like

```ts
export type MyRealOrdersRecord = OrdersRecord<{ foo: string}>
```

Then I'd use that everywhere in my code.

Agree about RecordBase, it can be skipped.

`pocketNow` just encapsulates the knowledge of how to serialize a date field for PocketBase. Unless I'm mistaken, passing a Date object like `client.records.create('orders', { orderTime: new Date() })` will not work.

**Comment by patmood** [comment]
Closing this to keep the issues clean. Some of the concepts like BaseRecord and alias types are incorporated already. I think the abstract types file should be done using the `--out pocketbase-types-abstract.ts` argument, and then extended  as necessary. There's not much value in generating the second file since the json types are unknown.
