### ISSUE TITLE
Idea: use interfaces with extends

### ISSUE THREAD

**Issue by garlandcrow** [patmood/pocketbase-typegen#14]
Was happy to find this as it seems it's solving the problem I have (needed typed records), but it would seem much more useful to have all the record types as interfaces that extend the BaseRecord interface so that we get all the things actually on the object. I modify my generated file in there afterwards and much easier than having to always use a type union.

**Comment by patmood** [comment]
Hey thanks, I just published v1.0.12 which adds Response types, eg `ProfilesResponse`. This is an intersection type with `BaseRecord` and has fields like id, created, updated etc.

This means the original `ProfilesRecord` type can still be used when creating records.

**Comment by karniv00l** [comment]
@patmood old code was released under v1.0.12 ;)

**Comment by patmood** [comment]
@karniv00l what are you seeing to suggest that? I did a quick sanity check from NPM and it seems ok

**Comment by karniv00l** [comment]
Oh sorry, something weird on my end, it was pulling the old version for me, same thing happened for: `npx pocketbase-typegen --version`, but I've tried again and now is good

**Comment by patmood** [comment]
Awesome good to hear!
