### ISSUE TITLE
General discussion 

### ISSUE THREAD

**Issue by benallfree** [patmood/pocketbase-typegen#2]
I wanted to talk about a couple issues that I frequently encounter:

1. With PocketBase, null values are not allowed. How is this addressed in this project? For example numeric fields will default to 0. I have discussed briefly the possibility of default values instead of just empty string or 0, but so far that is not a feature. 
2. For a json field, it would be great to generate one generic type param per json field so the user could create a derived type that defines the expected structure
3. BaaS types tend to change more often than traditional backends. Any thoughts on versioning types?

**Comment by patmood** [comment]
Thanks for the comments. I plan on building a larger PocketBase app next and will be able to get some more practical experience with this package.

1. Like you said, when you fetch a record it will have a value for every field (even if it's a default value). I typed it with optional fields for things that aren't marked as required. This is so the type is accurate when you update a record. You may want to create or update a record without some fields, so the type will allow that and be consistent with what PocketBase expects.
2. Interesting idea about JSON fields. I'll experiment with this.
3. Being able to change the schema on the fly is a double edge sword. You just have to be careful your changes are backwards compatible until you update the types. Personally, I plan to prevent schema changes in prod and only update it in dev, along with the types. Type generation + checking will be part of the CI pipeline. I'm not sure how versioning would work but open to suggestions.

**Comment by patmood** [comment]
added JSON generics in `1.0.10`. I'll close since there's no action items but any other discussion is also welcome
