### ISSUE TITLE
Question/Request: Generate types for the list request payloads as well? 

### ISSUE THREAD

**Issue by espy** [patmood/pocketbase-typegen#20]
First off, this is _sooooo useful_, many thanks!

However, I immediately found myself extending the types one level outward to include list request data like `page, perPage` etc.:

So, Pocketbase-Typegen gives me this for one of my records:

```typescript
export type TimeEntriesRecord = {
	start: IsoDateString
	end: IsoDateString
	description?: string
	project: RecordIdString
	user: UserIdString
}

export type TimeEntriesResponse = TimeEntriesRecord & BaseRecord
```

Wrapping that in the generic list response would be:

```typescript
export type ViewCollectionResponse = {
  page: number
  perPage: number
  totalItems: number
  totalPages: number
}

export type TimeEntriesViewCollectionResponse = ViewCollectionResponse & { items: TimeEntriesResponse[] }
```

and now I can do stuff like: 

```typescript
const fetchTimeEntries = async (): Promise<TimeEntriesViewCollectionResponse> => {
  const response = await fetch('http://127.0.0.1:8090/api/collections/time_entries/records?expand=project,project.customer', {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'User [TOKEN]',
    }
  })
  if (!response.ok) {
    throw new Error('Network response was not ok')
  }
  return response.json()
}

```
…which is pretty nice.

Would automatically adding one of these composed types per collection be a useful extension of this project, or is there a better, more abstract way to do this neatly in my code?

**Comment by patmood** [comment]
Glad this package is useful! Your suggestion makes sense, especially when using the rest API. Until now I have mostly had the pocketbase SDK in mind which will provide these fields for you. I'll take a look and add something soon!

**Comment by patmood** [comment]
@espy I looked into this for the new v0.8.0 PocketBase version. `ListResult<M>` is exported from the official pocketbase package, which means you can do this:

```
import { Collections, SomeRecordResponse } from "./pocketbase-types"
import type { ListResult } from "pocketbase"

async function collectionFetch(
  collection: Collections
): Promise<ListResult<SomeRecordResponse>> {
  return (
    await fetch(`${POCKETBASE_URL}/api/collections/${collection}/records`)
  ).json()
}
``` 

I think it makes the most sense to use the "official" types wherever possible. If you do `import type` it should prevent any bundle bloating.

Does that work for your use case?

**Comment by espy** [comment]
Thanks for both answers, that was really helpful. I think I’ll opt for the SDK from here on out, but still great you pointed out the `ListResult` type and how to get that.
