### ISSUE TITLE
expand? the props don't show up?

### ISSUE THREAD

**Issue by Brunowilliang** [patmood/pocketbase-typegen#23]
![Screen Shot 2022-11-21 at 22 25 30](https://user-images.githubusercontent.com/41432581/203191667-f324c40c-53bd-4db6-b2b8-cf30bd1f495e.png)
![Screen Shot 2022-11-21 at 22 26 34](https://user-images.githubusercontent.com/41432581/203192208-1eadd1b5-48a6-4db4-8a69-a53e28162e25.png)
![Screen Shot 2022-11-21 at 22 27 14](https://user-images.githubusercontent.com/41432581/203192548-6b59c5d4-c516-40e6-bb44-0de8bd935754.png)

**Comment by Brunowilliang** [comment]
in my generated file it appears like this...

`/**
* This file was @generated using pocketbase-typegen
*/

export enum Collections {
	Professionals = "professionals",
	Schedules = "schedules",
	Services = "services",
	Users = "users",
}

// Alias types for improved usability
export type IsoDateString = string
export type RecordIdString = string

// System fields
export type BaseSystemFields = {
	id: RecordIdString
	created: IsoDateString
	updated: IsoDateString
	collectionId: string
	collectionName: Collections
	expand?: { [key: string]: any }
}

export type AuthSystemFields = {
	email: string
	emailVisibility: boolean
	username: string
	verified: boolean
} & BaseSystemFields

// Record types for each collection

export type ProfessionalsRecord = {
	name?: string
	company?: RecordIdString
}

export type SchedulesRecord = {
	provider?: RecordIdString
	user?: RecordIdString
	professional?: RecordIdString
	service?: RecordIdString
	day?: string
	hour?: string
}

export type ServicesRecord = {
	name?: string
	price?: string
	duration?: string
	professional?: RecordIdString
}

export type UsersRecord = {
	company_name?: string
	name?: string
	avatar?: string
	phone?: string
	cpf?: string
	cnpj?: string
	provider?: boolean
	city?: string
}

// Response types include system fields and match responses from the PocketBase API
export type ProfessionalsResponse = ProfessionalsRecord & BaseSystemFields
export type SchedulesResponse = SchedulesRecord & BaseSystemFields
export type ServicesResponse = ServicesRecord & BaseSystemFields
export type UsersResponse = UsersRecord & AuthSystemFields

export type CollectionRecords = {
	professionals: ProfessionalsRecord
	schedules: SchedulesRecord
	services: ServicesRecord
	users: UsersRecord
}`

**Comment by patmood** [comment]
@Brunowilliang how are you getting `p` in the code snipped above? Are you using `getOne` or `getList` from the pocketbase sdk?

- `getOne` just returns a record, so there is no `item` field. It would just be `p.expand`
- `getList` returns an object with a list of items, so it would be something like `p.items[0].expand`

**Comment by Brunowilliang** [comment]
hi @patmood, i am using method .getFullList()
![Screen Shot 2022-11-22 at 11 35 46](https://user-images.githubusercontent.com/41432581/203341219-88849c1d-e0e4-433a-854c-2c5bf89ca37f.png)

**Comment by Brunowilliang** [comment]
@patmood ? Is correct?

**Comment by patmood** [comment]
Looks correct. `response` will just be an array of `SchedulesResponse`.

eg `response[0].expand.user`

The `expand` field of each item won't be typed as there is no way to infer it. What I could do is add a generic argument so the expand field is types.

Once added, it would allow you to do:

```typescript
type ScheduleExpand {
  user: UsersResponse
  professional: ProfessionalsResponse
  service: ServicesResponse
}
getFullList<SchedulesResponse<ScheduleExpand>>(...)
```
This package can't generate `ScheduleExpand` for you though, you'd need to type it yourself depending on how you expand.

**Comment by Brunowilliang** [comment]
@patmood  Strange, I can't generate even that strange...

**Comment by patmood** [comment]
I will close this and add a new issue for adding generic expand props
