### ISSUE TITLE
Merge with Pocketbase js-sdk

### ISSUE THREAD

**Issue by mbnoimi** [patmood/pocketbase-typegen#26]
I liked this project a lot. Have you considered to merge it with the official sdk?
You just need to make a tiny modification then send a PR to them

**Comment by patmood** [comment]
Thanks! I do think everyone using pocketbase + typescript should use this library :) However, it is self contained and has no dependencies on the official SDK, so it probably makes sense to keep it separate. Feel free to suggest any improvements!
