### ISSUE TITLE
Type "editor" is not supported

### ISSUE THREAD

**Issue by Sadragos** [patmood/pocketbase-typegen#31]
I'm using pocketbase 0.12.2 and have a collection with one field of type editor. When trying to generate types for that field I get this error `Error: unknown type editor found in schema`.

The field should be treated as text as it's just a default text with included html.

This is what the definition looks like in the exported json:
```json
      {
        "id": "x2mxxjff",
        "name": "description",
        "type": "editor",
        "system": false,
        "required": false,
        "unique": false,
        "options": {}
      },
```

**Comment by patmood** [comment]
Thanks for reporting! This was recently added in pocketbase. 

I’ll fix the type and change that error to a warning. If any new fields are added in the future they can be typed as unknown until this package is updated.

**Comment by patmood** [comment]
fixed in https://github.com/patmood/pocketbase-typegen/pull/32
