### ISSUE TITLE
Error when trying to generate types from remote url

### ISSUE THREAD

**Issue by andres-vizcaino** [patmood/pocketbase-typegen#55]
Hi I am trying to generate the types from a remote url and I get this error from the library.

What can I try to do?

![image](https://user-images.githubusercontent.com/94866827/231879248-0b476792-247c-40f0-bb12-5b5f331900a1.png)

**Comment by patmood** [comment]
Which version of pocketbase and which version of this package are you using?

**Comment by patmood** [comment]
@andres-vizcaino also try removing the trailing slash from the URL. If that fixes it I'll add better error handing

**Comment by andres-vizcaino** [comment]
I confirm, I removed the / and it worked!

We could leave in the documentation on this point? I think it wouldn't be out of place

**Comment by einarpersson** [comment]
I am not sure but I suspect it has something to do with the url naming. When I rename branch, which controls the db-url, it works. I'll post more info when I have it.

**Comment by patmood** [comment]
v1.1.8 will now log the fetch errors. That should give more insight into where/how the request is failing. Let me know if that reveals any more issues on the package side.
