### ISSUE TITLE
Empty record types should use object instead of {}

### ISSUE THREAD

**Issue by impact-merlinmarek** [patmood/pocketbase-typegen#56]
When using an empty auth collection the generated record type becomes `{}`, e.g.:

```
export type EmptyAuthRecord = {}
```

eslint made me aware that the `{}` type does not denote any object but any non-nullish value, i.e. this is valid code:

```
const record: EmptyAuthRecord = 7
const record2: EmptyAuthRecord = "foo"
```

I think empty records should use the type `Record<string, never>` (does not allow any properties) or at least `object` (does allow additional properties).

**Comment by patmood** [comment]
Makes sense! I'll update this
