### ISSUE TITLE
Proposal: Record fields should be required within the Response types

### ISSUE THREAD

**Issue by impact-jenssteffens** [patmood/pocketbase-typegen#58]
As discussed in #2 fields that are not marked as required are typed as optional in the Record types.
However this is not accurate for the Response types. As Pocketbase always returns a value for every field, all the fields should be markes as required within the Response types.

So instead of
```
export type UsersResponse = UsersRecord & BaseSystemFields
```

I suggest to type it like this:
```
export type UsersResponse = Required<UsersRecord> & BaseSystemFields
```

This would reflect the behavior of Pocketbase more accurately.

**Comment by patmood** [comment]
That's an interesting idea. I didn't know about `Required`. I agree that could be more accurate.

Have the optional fields been causing any issues? My original thinking was that it would encourage checking for unexpected falsy default value

**Comment by impact-jenssteffens** [comment]
It's not really an issue, but especially within larger projects the checking becomes very tedious, which is unnecessary in my opinion. Most of the time I want to use Response data to display it on screen and I have to think about how to display optional data anyway.

So now I have the situation, that the typescript language server complains about most of the fields for that they could be 'undefined', although this is not the case with the default Pocketbase behavior. The solution would be either to type all optional fields as
```
<type> | undefined
```
and add the corresponding checks or change the typing of the Response record, as I suggested.

**Comment by patmood** [comment]
Cool I think this will be backwards compatible too. I was originally trying to avoid having separate request and response type but this is a good solution 👍 Thanks for the suggestion
