### ISSUE TITLE
Is there a way to force a column type?

### ISSUE THREAD

**Issue by ByScripts** [patmood/pocketbase-typegen#64]
Hi, first I would like to thank you for this tool.

Here is my problem:

I created a view with this query:

```sql
SELECT
  a.id,
  a.name,
  COALESCE(SUM(o.amount), 0) as balance
FROM accounts AS a
  LEFT JOIN operations AS o ON o.account = a.id
  GROUP BY a.id
```

This way, the generated `balance` column can't be empty, it will always be a number.

Unfortunately, the schema generated for this column by PocketBase is as follows:

```json
 {
    "id": "bizfjmx2",
    "name": "balance",
    "type": "json",
    "system": false,
    "required": false,
    "options": {}
}
```

Thus, the generated type is:
```ts
export type AccountsWithBalanceRecord<Tbalance = unknown> = {
    name: string
    user: RecordIdString
    balance?: null | Tbalance
}
```

The problem here, is that even with `AccountsWithBalanceRecord<number>` the `balance` is configured as potentially missing or `undefined` or `null`, which in my case is incorrect.

Since the table schema type is `view`, couldn't the generated type be:

```ts
export type AccountsWithBalanceRecord<Tbalance = unknown> = {
    name: string
    user: RecordIdString
    balance: Tbalance
}
```

If not, do you think of any other idea to circumvent that?

Maybe a CLI option to handle these cases? (ie. `--force-type=accounts_with_balance.balance:number`)

Or a configuration file which would allow advanced configuration?

The only way I found right now is to down and edit schema as json before generating types, or edit the generated types after each generation.

Thank you.

**Comment by patmood** [comment]
Thanks for flagging the issue! 

If you use `AccountsWithBalanceResponse` (`Response` rather than `Record`) there will be no optional types since pocketbase uses defaults.

I think the root cause here is pocketbase thinking the `balance` field is JSON type. I think actual generated types from this library is expected behavior.

You can help pocketbase infer the right type by explicitly casting it in the query like this:
```
SELECT
  a.id,
  a.name,
  CAST(COALESCE(SUM(o.amount), 0) as REAL) as balance
FROM accounts AS a
  LEFT JOIN operations AS o ON o.account = a.id
GROUP BY a.id
```

This should make `balance` a number instead of json

**Comment by ByScripts** [comment]
Wow, thank you very much for your answer!

Using `CAST` is a really good idea; it indeed fixes the typing issue. Now `balance` is correctly defined as `balance?: number`

> If you use AccountsWithBalanceResponse there will be no optional types since pocketbase uses defaults.

It was not the case, so I looked further and found [this (fixed) issue](https://github.com/patmood/pocketbase-typegen/issues/58).

So, if this could help somebody else, it was because of npm cache.

Running `npx pocketbase-typegen` still uses the currently installed version.

Running `npx pocketbase-typegen@latest` fixes the problem.

Again, thank you for your help, which fixed my issue 👍🏻
