### ISSUE TITLE
Always include Texpand type parameter in Response types

### ISSUE THREAD

**Issue by impact-merlinmarek** [patmood/pocketbase-typegen#66]
Thanks for providing this tool.

Currently the Texpand type parameter is omitted for collections with no relation fields, see
https://github.com/patmood/pocketbase-typegen/blob/edb4d7db2c88aa15c6c9d1fbc91dcdf728268874/src/generics.ts#L28-L30
and
https://github.com/patmood/pocketbase-typegen/blob/edb4d7db2c88aa15c6c9d1fbc91dcdf728268874/src/generics.ts#L37-L39

Using indirect expand (https://pocketbase.io/docs/expanding-relations/#indirect-expand) we can still create responses that contain an expand property (users has no relation field and posts has a single relation to users):

```
const response = await pb
  .collection(Collections.Users)
  .getFullList<UsersResponse>({
    expand: "posts(user)",
  })

console.log(response)
```
output:
<pre>
[
  Record {
    avatar: '',
    collectionId: '_pb_users_auth_',
    collectionName: 'users',
    created: '2023-06-21 13:57:12.251Z',
    emailVisibility: false,
    <b>expand: { 'posts(user)': [Array] },</b>
    id: 'ziqx1tmedvn27yi',
    name: '',
    updated: '2023-06-21 13:57:12.251Z',
    username: 'demouser',
    verified: false
  }
]
</pre>

I think the Texpand type parameter should be included in all response types so they can be used with indirect expands as well.

**Comment by patmood** [comment]
Thank you for pointing this out! Will fix

**Comment by patmood** [comment]
@impact-merlinmarek let me know how v1.1.10 goes for you

**Comment by impact-merlinmarek** [comment]
Wow that was fast, thanks. Just tried it and it works as expected.
