### ISSUE TITLE
Collection name to records-type mapping

### ISSUE THREAD

**Issue by anbraten** [patmood/pocketbase-typegen#7]
It would be nice to have some mapping which would map the collection names to the specific record types like this:

```ts
export type CollectionRecords {
	profiles: ProfilesRecord;
	notifications: NotificationsRecord;
}

export type ProfilesRecord = {
	userId: string;
	name?: string;
	avatar?: string;
}

export type NotificationsRecord = {
	type: string;
        message: string;
	read: boolean;
}
```

This way we could write a wrapper like this:

```ts
function getOne<T extends keyof CollectionRecords>(collection: T, id: string): Promise<CollectionRecords[T]> {
  // ...
}
```

Which could be used like:

```ts
const myId = '123';
const notification = await getOne('notifications', myId);
```

And `notification` would directly get the correct type. 

How do you use the current `Collections` enum?

---

Thanks for this nice project.

**Comment by patmood** [comment]
Thanks, this is a great idea! Just published and it's available in 1.0.8
