### ISSUE TITLE
relation field generated type ignores "multiple" attribute

### ISSUE THREAD

**Issue by jkdoshi** [patmood/pocketbase-typegen#71]
First of all - Thank you for creating `pocketbase-typegen`! It saves me from myself every day!

Now, the issue ... I have the following PocketBase collection `projects` with a `users` relation field with `multiple` flag ON:
![image](https://github.com/patmood/pocketbase-typegen/assets/2412869/b2519680-813d-44bd-8a4f-1404c2896706)

But pocketbase-typegen generates a `users` field that is just a `RecordIdString` instead of an array `RecordIdString[]`:

```
export type ProjectsRecord<Tconfig = unknown> = {
	// other fields ...
	users?: RecordIdString
}
```

This does not match PocketBase's behavior, which returns an array of strings instead of a single comma-separated string of user-ids.

Shouldn't the generated type be `RecordIdString[]`?

**Comment by patmood** [comment]
Hey which version of `pocketbase-typegen` are you using? There is logic to handle this and it seems to be working. Perhaps an update will fix your issue

**Comment by jkdoshi** [comment]
You're absolutely right. I have using version 1.1.2. Upgrading to 1.1.11 fixes my issue.

Thank you!
