### ISSUE TITLE
Feature request: consider adding _admins collection

### ISSUE THREAD

**Issue by Plorenzo** [patmood/pocketbase-typegen#73]
Currently the default admin collection in Pocketbase is not supported. It would be great if it was part of the generated collections.

**Comment by patmood** [comment]
I dont see `admins` in the pocketbase schema so it might not be possible. What's the use case for this?

**Comment by patmood** [comment]
I had another look and the pocketbase js-sdk already provides typing for this, so it should be automatic 🎉 Since you can't edit the admin fields they are built into the SDK, no need to generate them
