### ISSUE TITLE
An enum member cannot have a numeric name. (TS2452 error)

### ISSUE THREAD

**Issue by Aragur** [patmood/pocketbase-typegen#74]
**Describe the bug**
Generating Types of a select field where `2023` and `2022`are the values, the TypeScript build results in the following error:
```
src/types/pocketbase.types.ts:38:2 - error TS2452: An enum member cannot have a numeric name.

38  "2023" = "2023",
    ~~~~~~

src/types/pocketbase.types.ts:39:2 - error TS2452: An enum member cannot have a numeric name.

39  "2022" = "2022",
    ~~~~~~


Found 2 errors in the same file, starting at: src/types/pocketbase.types.ts:38
```

**Versions**
pocketbase-typegen version:  1.1.11
pocketbase version: 0.17.2

**Comment by patmood** [comment]
Good find, I didn't know about this. Fixed using a prefix ("E" for "Enum") and I'll release now
