### ISSUE TITLE
Record was used before it was defined

### ISSUE THREAD

**Issue by karniv00l** [patmood/pocketbase-typegen#8]
Hi, any chance to have the order of definitions changed?

<img width="725" alt="Screenshot 2022-10-19 at 23 42 15" src="https://user-images.githubusercontent.com/3144291/196810286-dda89c22-9be4-43ad-9c2d-37fb48d3e551.png">

**Comment by patmood** [comment]
Which linter/rule is this so I can reproduce? It should work fine right now but I don't mind updating it to make the linter happy.

**Comment by karniv00l** [comment]
That will be this one: https://eslint.org/docs/latest/rules/no-use-before-define

**Comment by patmood** [comment]
Updated this in 1.0.9 🚀
