### ISSUE TITLE
I'm not understanding how to combine types to create a PB User

### ISSUE THREAD

**Issue by locohost** [patmood/pocketbase-typegen#84]
I looked through the examples and tried to answer my own question but wasn't able to do so. I'm trying to create a Pocketbase "Users" record. None of the various combinations of the generated types will provide types for all needed fields. I'm sure I missing something dumb but I just can't work it out. Here is a screen clip from my auth.ts code.

![image](https://github.com/patmood/pocketbase-typegen/assets/132458/17934c4b-e3c6-4ff1-a068-ec83b201a6c7)

Thank you, thank you, thank you for any advice. I'm stuck :-(

**Comment by patmood** [comment]
If you hover the `.create(` part, it will show you the expected type. It should just be be `UsersResponse`.

Let me know if this makes sense. There may be a bug with the new casting feature

**Comment by patmood** [comment]
This is a bug caused by the `create` type being different to the response type. Follow https://github.com/pocketbase/js-sdk/issues/254 for updates.

**Comment by patmood** [comment]
@locohost what is the actual error you're seeing?

**Comment by locohost** [comment]
> @locohost what is the actual error you're seeing?

I guess it's not really any error. It's just me not understanding how to use the generated types to see all the props on a model. In this case the User model. It's always missing types for one or more User props. In my mind I think I should just type a JSON object as UsersRecord or UsersResponse and all the User props will by typed show no red error squiggles. But this is not the case for me. It seems I have to combine multiple types in a certain way to have all props typed.

Does above make sense? I think it's just me missing something on how to use the multiple types, no error :-)

**Comment by patmood** [comment]
Sorry I misunderstood this issue. I think what you want is `const data: UsersRecord = { ... }`. That will show give you type hints of the fields you need, which ones are required, etc

After you call `pb.collection('users').create(data)` the resulting object will be `UsersResponse` type. This is similar but has extra fields added by pocketbase, like the id, date created etc.

Let me know if that works for you

**Comment by locohost** [comment]
Problem with typing data as **UsersRecord**  is it's missing **username** field type...

![image](https://github.com/patmood/pocketbase-typegen/assets/132458/9828cf11-724d-44e2-98cb-01f11019fea7)

**Comment by patmood** [comment]
I see - this is an issue. I'll need to think about the best way to fix it. For now just do `UsersRecord & { username: string }`
