### ISSUE TITLE
Add `--watch` option

### ISSUE THREAD

**Issue by babakfp** [patmood/pocketbase-typegen#88]
Hi

I think it could be useful if we had a feature to watch for the changes and regenerate the types.

**Comment by patmood** [comment]
This was discussed in https://github.com/patmood/pocketbase-typegen/pull/76

I think it's better to do outside of the library, for example you could use a script in your package.json like this to poll your schema:
```
  "scripts": {
    "typegen:watch": "while true; do pocketbase-typegen --url https://myproject.pockethost.io --env; sleep 15; done"
  }
  ```
