### ISSUE TITLE
Union type instead of enum type

### ISSUE THREAD

**Issue by p-dros** [patmood/pocketbase-typegen#91]
I've noticed a problem. Whenever the typegen is generating types for multiselect field it's using `enums ` that in some scenarios seems to be unnecessary.

```typescript
// Now
export enum CoursesSeasonOptions {
  'summer' = 'summer',
  'winter' = 'winter',
}

// Then
export type CoursesSeasonOptions = 'summer' | 'winter'
```
Could you explain me reason on using enums? 
Could your introduce unions types for these filed as an option in a command?

**Comment by patmood** [comment]
This is so you get a js object that can be used to render the options. `CoursesSeasonOptions` can be imported as a value.

Unless there's a good reason to use one over the other, I think its best to minimize the number of CLI options.
