### ISSUE TITLE
CLI "-e" flag not working

### ISSUE THREAD

**Issue by p-dros** [patmood/pocketbase-typegen#95]
**Describe the bug**
Pocketbase Typegen CLI is not correctly parsing `-e` flag.

Not Working:
```bash
pnpm dlx pocketbase-typegen -e ./.env.local --out ./src/types/pocketbase.ts

(...)

Missing schema path. Check options: pocketbase-typegen --help
```

Working

```bash
pnpm dlx pocketbase-typegen --env ./.env.local --out ./src/types/pocketbase.ts

(...)

Created typescript definitions at ./src/types/pocketbase.ts
```

**Versions**
pocketbase-typegen version: v1.2.1

**Comment by patmood** [comment]
Thanks for flagging. Looks like this probably conflicts with the `--email` option. I'll remove the short hand option and only allow `--env`
